process.env.JWT_SECRET = 'test-secret-key-for-testing-only'
process.env.DB_HOST = 'localhost'
process.env.DB_NAME = 'test_phoenix'
process.env.DB_USER = 'root'
process.env.DB_PASSWORD = ''
process.env.PORT = '0'
